version: "3.7"

services:  
  adventureworks:
    container_name: adventureworks
    networks: 
      - env_network
    ports: 
      - 8085:1433
    environment:
      MSSQL_SA_PASSWORD: "PaSSw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    build: 
      context: .\temp\sqlserverimage\
      dockerfile: Dockerfile

networks: 
  env_network:
    name: external_services