version: "3.7"

services:  
  adventureworks:
    container_name: adventureworks
    networks: 
      - env_network
    ports: 
      - 8085:1433
    environment:
      MSSQL_SA_PASSWORD: "PaSSw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    build: 
      context: .\temp\sqlserverimage\
      dockerfile: Dockerfile
  
  awslocalstack:
    container_name: awslocalstack
    image: localstack/localstack
    ports:
      - 4583:4583
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    networks: 
      - env_network
    environment: 
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - SERVICES=ssm
      - PORT_WEB_UI=${PORT_WEB_UI- }
    volumes:
      - ./localstack-init:/docker-entrypoint-initaws.d

networks: 
  env_network:
    name: external_services