version: "3.7"

services:
  dotnetlambda21:
    build: 
      target: publish
      context: .
      dockerfile: dotnet21.Dockerfile
    volumes:
       - ./output:/out
       
  dotnetlambda30:
    build: 
      target: publish
      context: ./DotnetLambda30
      dockerfile: Dockerfile
    volumes:
       - ./output:/out

  dotnetlambda21withef:
    build: 
      target: publish
      context: ./DotnetLambda21WithEf
      dockerfile: Dockerfile
    volumes:
       - ./output:/out

  dotnetlambda30withef:
    build: 
      target: publish
      context: ./DotnetLambda30WithEf
      dockerfile: Dockerfile
    volumes:
       - ./output:/out