version: "3.7"

services:  
  dotnetlambda21:    
    build: 
      target: tests
       
  dotnetlambda30:
    build: 
      target: tests

  dotnetlambda21withef:
    networks: 
      - env_network
    external_links:
      - adventureworks
    build: 
      target: tests

  dotnetlambda30withef:
    networks: 
      - env_network
    external_links:
      - adventureworks
    build: 
      target: tests

networks: 
  env_network:
    external: 
      name: external_services