version: "3.7"

services:  
  dotnetlambda21:    
    build: 
      target: tests
       
  dotnetlambda30:
    build: 
      target: tests

  dotnetlambda21withef:
    build: 
      target: tests

  dotnetlambda30withef:
    build: 
      target: tests