version: "3.7"

services:
  dotnetlambda21:
    build: 
      context: ./DotnetLambda21
      dockerfile: Dockerfile
    volumes:
       - ./output:/out
       
  dotnetlambda30:
    build: 
      context: ./DotnetLambda30
      dockerfile: Dockerfile
    volumes:
       - ./output:/out